Repository hashgraph/hedera-accelerator-defi-dex-ui, pull requests merged in 2023-08, with the labels that each got.

#218 Fix-US34370-TA99546: HBAR Association to wallet in Swap, Fix Cancel Button Not visible for Governance
  src/dex-ui/pages/CreateProposal/ProposalForms/ContractUpgradeProposalForm.tsx
  src/dex-ui/pages/CreateProposal/ProposalForms/TextProposalForm.tsx
  src/dex-ui/pages/CreateProposal/ProposalForms/TokenTransferProposalForm.tsx
  src/dex-ui/pages/Governance/VotingPower/ManageVotingPower.tsx
  src/dex-ui/pages/ProposalDetails/ProposalDetailsControls.tsx
  src/dex-ui/pages/ProposalDetails/useProposalDetails.tsx
  src/dex-ui/services/constants.ts
  src/dex-ui/store/swapSlice/swapSlice.ts
Labels: Feature Enhancement

#219 Fix: Error conditions when token is already associated
  src/dex-ui-components/WalletConnection/WalletTokenAssociation.tsx
Labels: enhancement

#217 feat: Pattern input constraints for Token Input component
  src/dex-ui-components/base/Form/index.ts
  src/dex-ui-components/base/Form/useFormTokenInputPattern.tsx
  src/dex-ui-components/base/Form/useHalfMaxButtons.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/types.ts
Labels: Feature Enhancement

#226 feat: Token Input component enhancements
  package.json
  src/dex-ui-components/WalletConnection/WalletConnection.tsx
  src/dex-ui-components/WalletConnection/WalletTokenAssociation.tsx
  src/dex-ui-components/base/Button/Button.tsx
  src/dex-ui-components/base/Button/SettingsButton.tsx
  src/dex-ui-components/base/Button/index.ts
  src/dex-ui-components/base/Button/styles/index.ts
  src/dex-ui-components/base/Form/FormTokenInput.tsx
  src/dex-ui-components/base/Form/index.ts
  src/dex-ui-components/base/FormInputList/FormInputList.tsx
  src/dex-ui-components/base/Inputs/FormInput.tsx
  src/dex-ui-components/base/Inputs/Input.tsx
  src/dex-ui-components/presets/LPTokenInput/LPTokenInput.tsx
  src/dex-ui-components/presets/SwapTokensForm/SwapConfirmation.tsx
  src/dex-ui-components/presets/TokenInput/TokenInput.tsx
  src/dex-ui-components/stories/Button.stories.mdx
  src/dex-ui-components/stories/Button.stories.tsx
  src/dex-ui-components/themes/buttonStyles.ts
  src/dex-ui-components/themes/index.ts
  src/dex-ui-components/themes/listStyles.ts
  src/dex-ui-components/themes/modalStyles.ts
  src/dex-ui/components/FormTokenInput/FormTokenInput.tsx
  src/dex-ui/components/FormTokenInput/FormTokenInputContext.tsx
  src/dex-ui/components/FormTokenInput/FormTokenInputHalfMaxButtons.tsx
  src/dex-ui/components/FormTokenInput/FormTokenInputLabel.tsx
  src/dex-ui/components/FormTokenInput/FormTokenInputSelectTokenButton.tsx
  src/dex-ui/components/FormTokenInput/FormTokenInputSelectTokenModal.tsx
  src/dex-ui/components/FormTokenInput/index.ts
  src/dex-ui/components/FormTokenInput/useFormTokenInputPattern.tsx
  src/dex-ui/components/FormTokenInput/useHalfMaxButtons.tsx
  src/dex-ui/components/index.ts
  src/dex-ui/hooks/hederaTokenService/useAccountTokenBalances.tsx
  src/dex-ui/hooks/index.ts
  src/dex-ui/pages/Governance/VotingPower/ManageVotingPower.tsx
  src/dex-ui/pages/ProposalDetails/ProposalDetailsControls.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx
  src/dex-ui/pages/dao/MintNFTModal.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DepositTokensModal.tsx
  src/dex-ui/theme/theme.ts
  yarn.lock
Labels: Feature Enhancement, New Feature

#225 feat/US34390: Multi Sig DAO Upgrade Part 1
  src/dex-ui/hooks/dao/index.ts
  src/dex-ui/hooks/dao/types.ts
  src/dex-ui/hooks/dao/useCreateMultiSigDAOUpgradeProposal.tsx
  src/dex-ui/hooks/dao/useDAOProposals.tsx
  src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOProposalTypeForm.tsx
  src/dex-ui/pages/dao/utils.ts
  src/dex-ui/routes/router.tsx
  src/dex-ui/services/DexService/dao/DAOService.ts
  src/dex-ui/services/HederaService/dao/MultiSigDAOService.ts
  src/dex-ui/services/HederaService/dao/type.ts
  src/dex-ui/services/JsonRpcService/utils.ts
  src/dex-ui/services/abi/MultiSigDAOFactory.json
  src/dex-ui/services/contractsUAT.json
Labels: New Feature

#232 feat: Created InlineAlert component
  src/dao/pages/ProposalDetailsPage/ProposalConfirmationDetails.tsx
  src/shared/ui-kit/components/Icons/ToastErrorIcon.tsx
  src/shared/ui-kit/components/Icons/ToastInfoIcon.tsx
  src/shared/ui-kit/components/Icons/ToastSuccessIcon.tsx
  src/shared/ui-kit/components/Icons/ToastWarningIcon.tsx
  src/shared/ui-kit/components/Icons/index.ts
  src/shared/ui-kit/components/InlineAlert/InlineAlert.tsx
  src/shared/ui-kit/components/InlineAlert/index.ts
  src/shared/ui-kit/components/Inputs/FormInput.tsx
  src/shared/ui-kit/components/index.ts
Labels: New Feature

#235 feat/US34423 NFT DAO Upgrade Proposal Execution
  src/dao/hooks/types.ts
  src/dao/hooks/useCreateDAOUpgradeProposal.tsx
  src/dao/hooks/useGovernanceDAOProposals.tsx
  src/dao/hooks/useLockNFTToken.tsx
  src/dao/hooks/useUnlockNFTToken.tsx
  src/dao/pages/DAOProposals/CreateDAOProposal.tsx
  src/dao/pages/DAOProposals/Forms/DAOContractUpgradeDetailsForm.tsx
  src/dao/pages/DAOProposals/Forms/DAOContractUpgradeReviewForm.tsx
  src/dao/pages/DAOProposals/Forms/DAOProposalTypeForm.tsx
  src/dao/pages/DAOProposals/types.ts
  src/dao/pages/ProposalCard.tsx
  src/dao/pages/ProposalDetailsPage/useGovernanceProposalDetails.tsx
  src/dao/pages/utils.ts
  src/dao/routes/router.tsx
  src/dao/services/DAOService.ts
  src/dao/services/contracts/NFTDAOService.ts
  src/dao/services/contracts/TokenDAOService.ts
  src/dao/services/types.ts
  src/dex/pages/Governance/VotingPower/ManageVotingPower.tsx
  src/dex/services/DexService/DexService.ts
  src/dex/services/DexService/governance/type.ts
  src/dex/services/JsonRpcService/utils.ts
  src/dex/services/abi/NFTDAOFactory.json
  src/dex/services/constants.ts
Labels: New Feature, enhancement

#243 Fix/DE21946-feat/US34453: fetch member list, updated threshold using new call contract api
  src/dao/hooks/useDAOProposals.tsx
  src/dao/services/DAOService.ts
  src/dex/hooks/governance/useAllProposals.tsx
  src/dex/hooks/governance/useProposal.tsx
  src/dex/pages/Governance/Governance.tsx
  src/dex/pages/ProposalDetails/useProposalDetails.tsx
  src/dex/services/DexService/governance/GovernanceService.ts
  src/dex/services/constants.ts
  src/shared/services/MirrorNodeService/MirrorNodeService.ts
Labels: enhancement
