Repository hashgraph/hedera-accelerator-defi-dex-ui, pull requests merged in 2023-07, with the labels that each got.

#184 feat/US34272: Update DAO Details For Multi Sig
  src/dex-ui/hooks/dao/index.ts
  src/dex-ui/hooks/dao/types.ts
  src/dex-ui/hooks/dao/useUpdateDAODetails.tsx
  src/dex-ui/pages/dao/CreateADAO/types.ts
  src/dex-ui/pages/dao/DAOSettings.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/Settings.tsx
  src/dex-ui/pages/dao/UpdateDAODetails/UpdateDAODetails.tsx
  src/dex-ui/pages/dao/UpdateDAODetails/UpdateDAODetailsForm.tsx
  src/dex-ui/pages/dao/UpdateDAODetails/UpdateDAODetailsReviewForm.tsx
  src/dex-ui/pages/dao/UpdateDAODetails/index.ts
  src/dex-ui/pages/dao/UpdateDAODetails/types.ts
  src/dex-ui/pages/dao/index.ts
  src/dex-ui/pages/dao/types.ts
  src/dex-ui/routes/router.tsx
  src/dex-ui/routes/routes.ts
  src/dex-ui/services/DexService/dao/DAOService.ts
  src/dex-ui/services/DexService/dao/types.ts
  src/dex-ui/services/HederaService/dao/MultiSigDAOService.ts
  src/dex-ui/services/HederaService/dao/type.ts
  src/dex-ui/services/abi/MultiSigDAO.json
  src/dex-ui/services/constants.ts
  src/dex-ui/services/contractsUAT.json
Labels: New Feature

#187 feat: US34301 Replaced Deprecated Proposal Forms and Routes
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOAddMemberDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAODeleteMemberDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOReplaceMemberDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOUpgradeThresholdDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/AddMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/AddMemberDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/AddMemberReviewForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/index.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/types.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/ChangeThreshold.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/ChangeThresholdDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/ChangeThresholdReviewForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/index.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/types.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/DeleteMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/DeleteMemberDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/DeleteMemberReviewForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/index.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/types.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/ReplaceMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/ReplaceMemberDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/ReplaceMemberReviewForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/index.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/types.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/Settings.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/index.ts
  src/dex-ui/routes/router.tsx
Labels: Improvement

#190 Feat/US34307: Update member and admin indicator when wallet state changes
  src/dex-ui/hooks/utils/index.ts
  src/dex-ui/hooks/utils/usePairedWalletDetails.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/MultiSigDAOReviewForm.tsx
  src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboard.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardHeader.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/MultiSigDAODashboard.tsx
  src/dex-ui/services/abi/MultiSigDAO.json
  src/dex-ui/services/abi/MultiSigDAOFactory.json
  src/dex-ui/services/contractsUAT.json
Labels: Feature Enhancement

#189 feat-US34294-US34320-US34321: Removed-json-rpc-from-governance
  src/dex-ui-components/base/CardList/CardList.tsx
  src/dex-ui-components/base/Icons/ActiveStepIcon.tsx
  src/dex-ui-components/base/Stepper/Stepper.tsx
  src/dex-ui/hooks/dao/index.ts
  src/dex-ui/hooks/dao/useCreateDAOTextProposal.tsx
  src/dex-ui/hooks/dao/useCreateDAOTokenTransferProposal.tsx
  src/dex-ui/hooks/dao/useCreateDAOUpgradeProposal.tsx
  src/dex-ui/hooks/dao/useFetchDAOLockedGovToken.tsx
  src/dex-ui/hooks/dao/useGovernanceDAOProposals.tsx
  src/dex-ui/hooks/governance/index.ts
  src/dex-ui/hooks/governance/types.ts
  src/dex-ui/hooks/governance/useAllProposals.tsx
  src/dex-ui/hooks/governance/useCanUserUnlockGODToken.tsx
  src/dex-ui/hooks/governance/useCreateContractUpgradeProposal.tsx
  src/dex-ui/hooks/governance/useCreateTextProposal.tsx
  src/dex-ui/hooks/governance/useCreateTokenTransferProposal.tsx
  src/dex-ui/hooks/governance/useFetchLockedGovToken.tsx
  src/dex-ui/hooks/governance/useGetLatestBlockNumber.tsx
  src/dex-ui/hooks/governance/useHasVoted.tsx
  src/dex-ui/hooks/governance/useLockGODToken.tsx
  src/dex-ui/hooks/governance/useProposal.tsx
  src/dex-ui/hooks/governance/useUnlockGODToken.tsx
  src/dex-ui/pages/CreateProposal/ProposalForms/ContractUpgradeProposalForm.tsx
  src/dex-ui/pages/CreateProposal/ProposalForms/TextProposalForm.tsx
  src/dex-ui/pages/CreateProposal/ProposalForms/TokenTransferProposalForm.tsx
  src/dex-ui/pages/Governance/Governance.tsx
  src/dex-ui/pages/Governance/VotingPower/useManageVotingPower.tsx
  src/dex-ui/pages/Pools/Pools.tsx
  src/dex-ui/pages/ProposalDetails/ProposalDetails.tsx
  src/dex-ui/pages/ProposalDetails/useProposalDetails.tsx
  src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/useGovernanceProposalDetails.tsx
  src/dex-ui/services/DexService/DexService.ts
  src/dex-ui/services/DexService/governance/GovernanceService.ts
  src/dex-ui/services/DexService/governance/type.ts
  src/dex-ui/services/HederaService/GovernorService.ts
  src/dex-ui/services/HederaService/HederaService.ts
  src/dex-ui/services/HederaService/dao/TokenDAOService.ts
  src/dex-ui/services/JsonRpcService/GodHolder.ts
  src/dex-ui/services/JsonRpcService/Governor.ts
  src/dex-ui/services/JsonRpcService/JsonRpcService.ts
  src/dex-ui/services/MirrorNodeService/MirrorNodeService.ts
  src/dex-ui/services/MirrorNodeService/types.ts
  src/dex-ui/services/abi/FTDAO.json
  src/dex-ui/services/abi/FTDAOFactory.json
  src/dex-ui/services/abi/GODHolder.json
  src/dex-ui/services/abi/GovernorCountingSimpleInternal.json
  src/dex-ui/services/constants.ts
  src/dex-ui/services/contractsUAT.json
  src/dex-ui/services/index.ts
  src/dex-ui/store/governanceSlice/type.ts
Labels: Feature Enhancement, Improvement

#194 feat/US34299: DAO Proposals Pagination
  src/dex-ui-components/base/Pagination/Pagination.tsx
  src/dex-ui/layouts/Page.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ProposalList.tsx
  src/dex-ui/services/MirrorNodeService/MirrorNodeService.ts
Labels: Feature Enhancement

#198 feat: Jul 20 demo enhancements (part 1)
  src/dex-ui-components/base/Form/FormDropdown.tsx
  src/dex-ui-components/base/Form/index.ts
  src/dex-ui-components/base/Inputs/FormInput.tsx
  src/dex-ui-components/base/RadioCard/RadioCard.tsx
  src/dex-ui-components/base/Select/SelectStyles.ts
  src/dex-ui-components/base/index.ts
  src/dex-ui/pages/Governance/VotingPower/GOVTokenDetails.tsx
  src/dex-ui/pages/Governance/VotingPower/ManageVotingPower.tsx
  src/dex-ui/pages/Governance/VotingPower/VotingPower.tsx
  src/dex-ui/pages/Governance/VotingPower/types.ts
  src/dex-ui/pages/Governance/VotingPower/useManageVotingPower.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/CreateTokenDAOGovernanceForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/TokenDAOVotingForm.tsx
  src/dex-ui/pages/dao/DAODashboard.tsx
  src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/types.ts
  src/dex-ui/pages/dao/DashboardHeader.tsx
  src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboard.tsx
  src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboardOverview.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardOverview.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalConfirmationDetails.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/GovernanceProposalDetailsPage.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/ProposalVoteModal.tsx
  src/dex-ui/routes/router.tsx
  src/dex-ui/services/DexService/dao/DAOService.ts
  src/dex-ui/services/HederaService/TokenService.ts
Labels: Feature Enhancement

#210 feat: Create and add Token Input component to Token Transfer form
  src/dex-ui-components/base/Form/FormTokenInput.tsx
  src/dex-ui-components/base/Form/index.ts
  src/dex-ui-components/base/Form/useHalfMaxButtons.tsx
  src/dex-ui-components/base/Inputs/FormInput.tsx
  src/dex-ui/pages/Governance/VotingPower/ManageVotingPower.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsComponents/ProposalActionDetails.tsx
  src/dex-ui/services/constants.ts
  src/dex-ui/store/walletSlice/walletSlice.ts
Labels: Feature Enhancement

#212 feat/US34367: Associate token to user wallet
  src/dex-ui-components/WalletConnection/WalletConnection.tsx
  src/dex-ui-components/WalletConnection/WalletTokenAssociation.tsx
  src/dex-ui-components/WalletConnection/index.ts
  src/dex-ui/hooks/token/index.ts
  src/dex-ui/hooks/token/types.ts
  src/dex-ui/hooks/token/useTokenAssociate.tsx
  src/dex-ui/services/HederaService/TokenService.ts
Labels: New Feature

#214 feat/US34370-TA99536: Added the Token Already Associated to wallet error in Token Association Flow
  src/dex-ui-components/WalletConnection/WalletTokenAssociation.tsx
  src/dex-ui/hooks/hederaTokenService/useFetchTokenData.tsx
  src/dex-ui/hooks/token/useTokenBalance.tsx
  src/dex-ui/pages/Governance/VotingPower/useManageVotingPower.tsx
Labels: Feature Enhancement

#216 feat/US34376: New Updated Contracts
  src/dex-ui/components/GetTokensButton.tsx
  src/dex-ui/services/DexService/dao/DAOService.ts
  src/dex-ui/services/constants.ts
  src/dex-ui/services/contractsUAT.json
Labels: enhancement
