Repository hashgraph/hedera-accelerator-defi-dex-ui, pull requests merged in 2023-06, with the labels that each got.

#163 feat/US34141: Routing enhancements for Create DAO flow with new Form Wizard Component
  src/dex-ui-components/base/Button/CopyTextButton.tsx
  src/dex-ui-components/base/Icons/CopyIcon.tsx
  src/dex-ui-components/base/Icons/RefreshIcon.tsx
  src/dex-ui-components/base/Icons/index.ts
  src/dex-ui-components/themes/layerStyles.ts
  src/dex-ui/components/Wizard/WizardForm.tsx
  src/dex-ui/pages/dao/CreateADAO/CreateADAOPage.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/CreateTokenDAOGovernanceForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/DAOTypeForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/ExistingTokenDAOGovernanceForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/MultiSigDAOReviewForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/MultiSigDAOVotingForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/TokenDAOReviewForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/constants.ts
  src/dex-ui/pages/dao/CreateADAO/index.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/AddMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/AddMemberDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/AddMemberReviewForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/types.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/ChangeThreshold.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/ChangeThresholdDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/ChangeThresholdReviewForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/types.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/DeleteMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/DeleteMemberDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/DeleteMemberReviewForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/types.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/ReplaceMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/ReplaceMemberDetailsForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/ReplaceMemberReviewForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/types.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/Settings.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/types.ts
  src/dex-ui/routes/router.tsx
  src/dex-ui/routes/routes.ts
  src/dex-ui/services/DexService/dao/DAOService.ts
  src/dex-ui/services/DexService/dao/types.ts
  src/dex-ui/services/HederaService/dao/MultiSigDAOService.ts
Labels: Feature Enhancement, Improvement

#165 feat: Notification System 2.0
  package.json
  src/dex-ui-components/base/Icons/ToastErrorIcon.tsx
  src/dex-ui-components/base/Icons/ToastInfoIcon.tsx
  src/dex-ui-components/base/Icons/ToastSuccessIcon.tsx
  src/dex-ui-components/base/Icons/index.ts
  src/dex-ui-components/base/Toast/Toast.tsx
  src/dex-ui-components/base/Toast/ToastContainer.tsx
  src/dex-ui-components/base/Toast/index.ts
  src/dex-ui-components/base/index.ts
  src/dex-ui-components/themes/index.ts
  src/dex-ui-components/themes/layerStyles.ts
  src/dex-ui-components/themes/linkStyles.ts
  src/dex-ui-components/themes/textStyles.ts
  src/dex-ui-components/themes/toastStyles.ts
  src/dex-ui/DEX.tsx
  src/dex-ui/hooks/dao/useApproveTransaction.tsx
  src/dex-ui/hooks/dao/useCreateAddMemberTransaction.tsx
  src/dex-ui/hooks/dao/useCreateChangeThresholdTransaction.tsx
  src/dex-ui/hooks/dao/useCreateDAO.tsx
  src/dex-ui/hooks/dao/useCreateDeleteMemberTransaction.tsx
  src/dex-ui/hooks/dao/useCreateMultiSigTransaction.tsx
  src/dex-ui/hooks/dao/useCreateReplaceMemberTransaction.tsx
  src/dex-ui/hooks/dao/useDAOs.tsx
  src/dex-ui/hooks/dao/useExecuteTransaction.tsx
  src/dex-ui/hooks/hederaTokenService/useCreateNonFungibleToken.tsx
  src/dex-ui/hooks/hederaTokenService/useCreateToken.tsx
  src/dex-ui/hooks/index.ts
  src/dex-ui/hooks/utils/index.ts
  src/dex-ui/hooks/utils/types.ts
  src/dex-ui/hooks/utils/useHandleTransactionSuccess.tsx
  src/dex-ui/pages/dao/CreateADAO/CreateADAOPage.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/CreateTokenDAOGovernanceForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/DAODetailsForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/DAOReviewForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/NFTDAOGovernanceForm.tsx
  src/dex-ui/pages/dao/DAODashboard.tsx
  src/dex-ui/pages/dao/DAOsListPage/DAOsListPage.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/AddMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/ChangeThreshold.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/DeleteMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/MultiSigDAODashboard.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/ReplaceMember.tsx
  src/dex-ui/pages/dao/SendTokenWizard/SendTokenWizard.tsx
  src/dex-ui/pages/dao/TokenTransactionDetails/TokenTransactionDetails.tsx
  src/dex-ui/theme/theme.ts
  yarn.lock
Labels: Feature Enhancement, Improvement

#166 feat/34254 Basic Layout structure for DAO Proposals form
  src/dex-ui-components/base/Dialogs/AlertDialog.tsx
  src/dex-ui-components/base/Icons/MemberIcon.tsx
  src/dex-ui-components/base/Icons/MessageIcon.tsx
  src/dex-ui-components/base/Icons/NewTokenIcon.tsx
  src/dex-ui-components/base/Icons/SuccessCheckIcon.tsx
  src/dex-ui-components/base/Icons/TextProposalIcon.tsx
  src/dex-ui-components/base/Icons/ToastErrorIcon.tsx
  src/dex-ui-components/base/Icons/ToastSuccessIcon.tsx
  src/dex-ui-components/base/Icons/TwoLayerSettingIcon.tsx
  src/dex-ui-components/base/Icons/index.ts
  src/dex-ui/pages/Governance/VotingPower/ManageVotingPower.tsx
  src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOAddMemberDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOAddMemberReviewForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAODeleteMemberDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAODeleteMemberReviewForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOProposalTypeForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOReplaceMemberDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOReplaceMemberReviewForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOTextProposalDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferReviewForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOUpgradeThresholdDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOUpgradeThresholdReviewForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DaoTextProposalReviewForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/index.ts
  src/dex-ui/pages/dao/DAOProposals/index.ts
  src/dex-ui/pages/dao/DAOProposals/types.ts
  src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardHeader.tsx
  src/dex-ui/pages/dao/index.ts
  src/dex-ui/routes/router.tsx
  src/dex-ui/routes/routes.ts
Labels: New Feature

#171 feat/US34277: Dynamic "Manage Voting Power Component" for GOV, NFT Dao and Governance
  src/dex-ui/hooks/governance/useCanUserUnlockGODToken.tsx
  src/dex-ui/hooks/governance/useFetchLockedGovToken.tsx
  src/dex-ui/hooks/governance/useLockGODToken.tsx
  src/dex-ui/hooks/governance/useUnlockGODToken.tsx
  src/dex-ui/hooks/token/useTokenBalance.tsx
  src/dex-ui/pages/Governance/Governance.tsx
  src/dex-ui/pages/Governance/VotingPower/VotingPower.tsx
  src/dex-ui/pages/Governance/VotingPower/useManageVotingPower.tsx
  src/dex-ui/pages/ProposalDetails/useProposalDetails.tsx
  src/dex-ui/pages/dao/DAODashboard.tsx
  src/dex-ui/pages/dao/DashboardHeader.tsx
  src/dex-ui/services/DexService/dao/DAOService.ts
  src/dex-ui/services/DexService/dao/types.ts
  src/dex-ui/services/HederaService/GovernorService.ts
  src/dex-ui/services/JsonRpcService/GodHolder.ts
  src/dex-ui/services/abi/GODHolder.json
  src/dex-ui/services/abi/GovernanceDAOFactory.json
  src/dex-ui/services/abi/NFTDAOFactory.json
  src/dex-ui/services/contractsUAT.json
Labels: Feature Enhancement, enhancement

#172 feat/US34247-US34246: Updated DAO Icon
  src/dex-ui-components/base/Icons/SelectImageIcon.tsx
  src/dex-ui-components/base/Icons/index.ts
  src/dex-ui/pages/dao/CreateADAO/forms/DAODetailsForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/DAOReviewForm.tsx
  src/dex-ui/pages/dao/DAOSettings.tsx
  src/dex-ui/pages/dao/DAOsListPage/DAOCard.tsx
  src/dex-ui/pages/dao/DAOsListPage/DAOsListPage.tsx
  src/dex-ui/pages/dao/DashboardHeader.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardHeader.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/MultiSigDAODashboard.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/Settings.tsx
  src/dex-ui/pages/dao/ProposalCard.tsx
Labels: Feature Enhancement

#173 feat: Changed dashboard tab to overview
  src/dex-ui/pages/dao/DAODashboard.tsx
  src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/MultiSigDAODashboard.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsPage.tsx
  src/dex-ui/pages/dao/SendTokenWizard/SendTokenWizard.tsx
  src/dex-ui/routes/router.tsx
  src/dex-ui/routes/routes.ts
Labels: enhancement

#176 feat/US34271: UI for Gov DAO Contract Upgrade Proposal
  src/dex-ui-components/base/Icons/SettingsToolIcon.tsx
  src/dex-ui-components/base/Icons/index.ts
  src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOContractUpgradeDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOContractUpgradeReviewForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOProposalTypeForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/index.ts
  src/dex-ui/pages/dao/DAOProposals/types.ts
  src/dex-ui/routes/router.tsx
  src/dex-ui/routes/routes.ts
Labels: New Feature

#174 feat/US34248-US34253: DAO Enhancements
  src/dex-ui-components/base/Icons/CancelledStepIcon.tsx
  src/dex-ui-components/base/Icons/CheckRightIcon.tsx
  src/dex-ui-components/base/Icons/GlobeIcon.tsx
  src/dex-ui-components/base/Icons/InstagramIcon.tsx
  src/dex-ui-components/base/Icons/TwitterIcon.tsx
  src/dex-ui-components/base/Icons/index.ts
  src/dex-ui/pages/dao/DAODashboard.tsx
  src/dex-ui/pages/dao/DAOSettings.tsx
  src/dex-ui/pages/dao/DashboardHeader.tsx
  src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboard.tsx
  src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboardOverview.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardOverview.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/MultiSigDAODashboard.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/Settings.tsx
  src/dex-ui/pages/dao/NFTDAODashboard/NFTDAODashboardOverview.tsx
  src/dex-ui/pages/dao/utils.ts
  src/dex-ui/routes/router.tsx
  src/dex-ui/services/DexService/dao/types.ts
Labels: enhancement

#177 feat: UI Enhancements + Sending Token Id to Transfer Token Form
  src/dex-ui-components/base/Breadcrumb/Breadcrumb.tsx
  src/dex-ui-components/base/Breadcrumb/__tests__/Breadcrumb.test.tsx
  src/dex-ui-components/themes/layerStyles.ts
  src/dex-ui/components/Wizard/WizardHeader.tsx
  src/dex-ui/layouts/CardGridLayout.tsx
  src/dex-ui/layouts/CardListLayout.tsx
  src/dex-ui/pages/CreateProposal/CreateNewProposal.tsx
  src/dex-ui/pages/CreateProposal/ProposalForms/ContractUpgradeProposalForm.tsx
  src/dex-ui/pages/CreateProposal/ProposalForms/CreateTokenProposalForm.tsx
  src/dex-ui/pages/CreateProposal/ProposalForms/TextProposalForm.tsx
  src/dex-ui/pages/CreateProposal/ProposalForms/TokenTransferProposalForm.tsx
  src/dex-ui/pages/dao/CreateADAO/CreateADAOPage.tsx
  src/dex-ui/pages/dao/DAODashboard.tsx
  src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOProposalTypeForm.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOTokenTransferDetailsForm.tsx
  src/dex-ui/pages/dao/DAOProposals/types.ts
  src/dex-ui/pages/dao/DAOSettings.tsx
  src/dex-ui/pages/dao/DAOsListPage/DAOCard.tsx
  src/dex-ui/pages/dao/DAOsListPage/DAOsListPage.tsx
  src/dex-ui/pages/dao/DashboardHeader.tsx
  src/dex-ui/pages/dao/GovernanceDAODashboard/GovernanceDAODashboardOverview.tsx
  src/dex-ui/pages/dao/MembersList.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AddMember/AddMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/AssetsList.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ChangeThreshold/ChangeThreshold.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardHeader.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardOverview.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DeleteMember/DeleteMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ReplaceMember/ReplaceMember.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/Settings.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/TransactionsList.tsx
  src/dex-ui/pages/dao/NFTDAODashboard/NFTDAODashboardOverview.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsHeader.tsx
  src/dex-ui/pages/dao/SendTokenWizard/SendTokenDetailsForm.tsx
  src/dex-ui/pages/dao/SendTokenWizard/SendTokenReviewForm.tsx
  src/dex-ui/pages/dao/SendTokenWizard/SendTokenWizard.tsx
  src/dex-ui/pages/dao/SendTokenWizard/index.ts
  src/dex-ui/pages/dao/SendTokenWizard/types.ts
  src/dex-ui/pages/dao/index.ts
  src/dex-ui/routes/router.tsx
  src/dex-ui/routes/routes.ts
Labels: Feature Enhancement

#181 feat: Additional UI Enhancements for MultiSig DAO v1
  src/dex-ui/pages/dao/CreateADAO/forms/MultiSigDAOVotingForm.tsx
  src/dex-ui/pages/dao/CreateADAO/forms/constants.ts
  src/dex-ui/pages/dao/DAOProposals/CreateDAOProposal.tsx
  src/dex-ui/pages/dao/DAOProposals/Forms/DAOProposalTypeForm.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/DashboardOverview.tsx
  src/dex-ui/pages/dao/MultiSigDAODashboard/ProposalList.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetails.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsComponents/ProposalActionDetails.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsComponents/ProposalTransactionDetails.tsx
  src/dex-ui/pages/dao/ProposalDetailsPage/ProposalDetailsPage.tsx
Labels: enhancement
